INTEGER,ALLOCATABLE::A(:,:),B(:,:),C(:,:)
READ*,I,J
ALLOCATE(A(I,J))
K=I
DO L=1,I
READ*,A(L,:)
ENDDO
READ*,I,J
ALLOCATE(B(I,J))
DO L=1,I
READ*,B(L,:)
ENDDO
ALLOCATE(C(K,J))
C=MATMUL(A,B)
DEALLOCATE(A,B)
DO I=1,K
M=0
DO L=1,(J+(J-1))
IF(MOD(L,2)==0)THEN
WRITE(*,'(A)',ADVANCE='NO') ' '
M=M+1
ELSE
WRITE(*,'(I0)',ADVANCE='NO') C(I,L-M)
ENDIF
ENDDO
PRINT*,''
ENDDO
END