INTEGER,ALLOCATABLE::A(:,:),B(:,:)
READ*,I,J
ALLOCATE(A(I,J),B(I,J))
DO L=1,I
READ*,A(L,:)
ENDDO
DO L=1,I
READ*,B(L,:)
ENDDO
DO K=1,I
M=0
DO L=1,(J+(J-1))
IF(MOD(L,2)==0)THEN
WRITE(*,'(A)',ADVANCE='NO') ' '
M=M+1
ELSE
WRITE(*,'(I0)',ADVANCE='NO') A(K,L-M)+B(K,L-M)
ENDIF
ENDDO
PRINT*,''
ENDDO
END