INTEGER::A(6)
READ*,N
DO L=1,N
READ*,A
X=SQRT(ABS(A(1)*1.-A(4))**2+ABS(A(2)*1.-A(5))**2)
J=A(3)+A(6)
K=ABS(A(3)-A(6))
IF(A(1)==A(4).AND.A(2)==A(5).AND.A(3)==A(6))THEN
PRINT 9,-1
ELSEIF(X>J.OR.X<K) THEN
PRINT 9,0
ELSEIF(X==J.OR.X==K) THEN
PRINT 9,1
ELSEIF(X<J.AND.X>K) THEN
PRINT 9,2
ENDIF
ENDDO
9 FORMAT(I0)
END